services:
  - type: web
    name: astro-circle-b
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python server/project/manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 9000 
      - key: DATABASE_URL
        value: postgresql://astro_4464_user:vjFHBudCL7EsM1ZVa7PJ2I6pBG8kZhpZ@dpg-d17qrpmmcj7s73c695ng-a.oregon-postgres.render.com:5432/astro_4464 
        