# Generated by Django 5.2.1 on 2025-06-11 13:46

from django.db import migrations, models
import uuid

def generate_usernames(apps, schema_editor):
    User = apps.get_model('app', 'User')
    for user in User.objects.all():
        if not user.username:
            user.username = f"user_{uuid.uuid4().hex[:8]}"
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_usernames),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, null=True, blank=True),
        ),
    ]
