# Generated by Django 5.2.1 on 2025-06-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
